---
- name: "Create JON User"
  user: 
    name: "{{jon_service_user}}"
    shell: /sbin/nologin
    state: present
  tags: [jon]

#- name: create rhq admin
#  postgresql_user: 
#    name: rhqadmin
#    password: "redhat@123"
#    login_password: "{{postgres_user_password|hash('md5')}}"
#  tags: [jon]

#- name: create rhq database
#  postgresql_db: 
#    name: rhq
#    login_password: "{{postgres_user_password|hash('md5')}}"
#    encoding: 'UTF-8'
#    owner: rhqadmin
#  tags: [jon]

- name: ceate JON install path
  file:
    path: "{{jon_install_path}}"
    owner: "{{jon_service_user}}"
    group: "{{jon_service_user}}"
    state: directory
  tags: [jon]

- name: install jon
  unarchive:
    src: "{{jon_installer_archive}}"
    dest: "{{jon_install_path}}"
    owner: "{{jon_service_user}}"
    group: "{{jon_service_user}}"
    creates: "{{jon_home}}"
  tags: [jon]

- name: create rhq directories
  file:
    path: "{{jon_install_path}}{{item}}"
    owner: "{{jon_service_user}}"
    group: "{{jon_service_user}}"
    state: directory
  with_items:
    - 'rhq-data'
    - 'rhq-agent'
  tags: [jon]

- name: JON control script
  template:
    src: jonctl.sh.j2
    dest: /usr/local/bin/jonctl.sh
    mode: 0755
  tags: [jon]

- name: RHQ Server Properties
  template:
    src: rhq-server.properties.j2
    dest: "{{jon_home}}/bin/rhq-server.properties"
    owner: "{{jon_service_user}}"
    group: "{{jon_service_user}}"
  tags: [jon]